//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod alerts;
pub mod contacts;
pub mod historicprice;
pub mod messages;
pub mod product;
pub mod shop;
pub mod shopposition;
