//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parsinglookup")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub shop_id: i32,
    pub max_page: i32,
    #[sea_orm(column_type = "Text")]
    pub product_table: String,
    #[sea_orm(column_type = "Text")]
    pub product: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub price: String,
    #[sea_orm(column_type = "Text")]
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::shop::Entity",
        from = "Column::ShopId",
        to = "super::shop::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Shop,
    #[sea_orm(has_many = "super::shopparsingrules::Entity")]
    Shopparsingrules,
}

impl Related<super::shop::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shop.def()
    }
}

impl Related<super::shopparsingrules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shopparsingrules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
