///! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
#[allow(unused_imports)]
pub use super::alerts::Entity as Alerts;
pub use super::contacts::Entity as Contacts;
pub use super::historicprice::Entity as Historicprice;
pub use super::messages::Entity as Messages;
pub use super::product::Entity as Product;
pub use super::shop::Entity as Shop;
pub use super::shopposition::Entity as Shopposition;
