//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::alerts::Entity as Alerts;
pub use super::contacts::Entity as Contacts;
pub use super::historicprice::Entity as Historicprice;
pub use super::messages::Entity as Messages;
pub use super::parsingcategory::Entity as Parsingcategory;
pub use super::parsinglookup::Entity as Parsinglookup;
pub use super::product::Entity as Product;
pub use super::proxy::Entity as Proxy;
pub use super::proxyparsingrules::Entity as Proxyparsingrules;
pub use super::proxysources::Entity as Proxysources;
pub use super::shop::Entity as Shop;
pub use super::shopparsingrules::Entity as Shopparsingrules;
pub use super::shopposition::Entity as Shopposition;
