//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod alerts;
pub mod contacts;
pub mod historicprice;
pub mod messages;
pub mod parsingcategory;
pub mod parsinglookup;
pub mod product;
pub mod proxy;
pub mod proxyparsingrules;
pub mod proxysources;
pub mod shop;
pub mod shopparsingrules;
pub mod shopposition;
