//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alerts::Entity")]
    Alerts,
    #[sea_orm(has_many = "super::historicprice::Entity")]
    Historicprice,
    #[sea_orm(has_many = "super::shopposition::Entity")]
    Shopposition,
}

impl Related<super::alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Alerts.def()
    }
}

impl Related<super::historicprice::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Historicprice.def()
    }
}

impl Related<super::shopposition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shopposition.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
